POST http://localhost:3000/login/
Content-Type : application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

GET http://localhost:3000/states/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzMyODcwMTM3fQ.gyBxxpIkhGMblyJxNk90KzCfJCTUMsMhXbEIcUdJX3Y

GET http://localhost:3000/states/1/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzMyODcwMTM3fQ.gyBxxpIkhGMblyJxNk90KzCfJCTUMsMhXbEIcUdJX3Y



POST http://localhost:3000/district/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzMyODcwMTM3fQ.gyBxxpIkhGMblyJxNk90KzCfJCTUMsMhXbEIcUdJX3Y
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}


GET http://localhost:3000/district/742/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzMyODcwMTM3fQ.gyBxxpIkhGMblyJxNk90KzCfJCTUMsMhXbEIcUdJX3Y


DELETE http://localhost:3000/district/742/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzMyODcwMTM3fQ.gyBxxpIkhGMblyJxNk90KzCfJCTUMsMhXbEIcUdJX3Y



PUT http://localhost:3000/district/766/
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzMyODcwMTM3fQ.gyBxxpIkhGMblyJxNk90KzCfJCTUMsMhXbEIcUdJX3Y

Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}


GET http://localhost:3000/states/4/stats
Authorization : bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzMyODcwMTM3fQ.gyBxxpIkhGMblyJxNk90KzCfJCTUMsMhXbEIcUdJX3Y
